### ISSUE TITLE
Use models from trends.earth-schemas where possible

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trendsearth-web#1]
@robertohuru - where possible, can we reuse the schemas defined in [ConservationInternational/trends.earth-schemas](https://github.com/ConservationInternational/trends.earth-schemas/tree/develop), for the models in [models.py](https://github.com/ConservationInternational/trendsearth-web/blob/main/job/models.py)? The `trends.earth-schemas` repo has the schemas currently used in the QGIS plugin and also in our cloud tools,  so would be great if we could use that as a single source of truth for the schemas.

**Comment by robertohuru** [comment]
@azvoleff I have noted this for our discussion on Monday. My intention was to use a database model for the schemas. Of course with the benefits of easier filtering and management of multiple users on a web environment. We can discuss next week what is handled by the API and what is taken up by the desktop client.
